# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abf388d8196184641b068c12fc59bd7aab5105f99fdfd1cc03d70a6b1f396b1b6d10d72fe56a2c8d8e62393b6f0af6b65d4cfd6cbe5ae2d56c0e95f104d8fa43

test:
  secret_key_base: a49f34a2c03237c84a8bee651883a599ee774f45275a62cdeaafbb3dea1c455984ccc6c8cab57a7f8cae80a3b010c7aa9176526173d9fd1a419329a2e5802890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
